# Generated by Django 6.0.1 on 2026-02-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=10)),
                ('year_level', models.CharField(max_length=3)),
                ('exam_type', models.CharField(choices=[('prelim', 'Prelim'), ('midterm', 'Midterm'), ('final', 'Final'), ('quiz', 'Quiz')], max_length=10)),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('identification', 'Identification'), ('enumeration', 'Enumeration'), ('essay', 'Essay'), ('mixed', 'Mixed')], default='multiple_choice', max_length=20)),
                ('scheduled_date', models.DateTimeField()),
                ('duration_minutes', models.IntegerField()),
                ('total_points', models.IntegerField()),
                ('passing_score', models.IntegerField()),
                ('instructions', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('total_points', models.IntegerField()),
                ('percentage', models.FloatField()),
                ('grade', models.CharField(max_length=5)),
                ('remarks', models.CharField(max_length=20)),
                ('answers', models.JSONField(default=dict)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('type', models.CharField(max_length=20)),
                ('options', models.JSONField(blank=True, null=True)),
                ('correct_answer', models.TextField()),
                ('points', models.IntegerField()),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
