# Generated by Django 6.0.1 on 2026-02-18 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='graded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examresult',
            name='is_graded',
            field=models.BooleanField(default=False),
        ),
    ]
