# Generated by Django 6.0.1 on 2026-02-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_cheatingviolation'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_practice',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('prelim', 'Prelim'), ('midterm', 'Midterm'), ('final', 'Final'), ('quiz', 'Quiz'), ('practice', 'Practice')], max_length=10),
        ),
    ]
