# Generated by Django 6.0.1 on 2026-03-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_examphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='examphoto',
            name='violation_reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='examphoto',
            name='capture_type',
            field=models.CharField(choices=[('start', 'Exam Start'), ('periodic', 'Periodic Check'), ('violation', 'Violation Detected'), ('suspicious', 'Suspicious Activity')], max_length=20),
        ),
    ]
