# Generated by Django 6.0.1 on 2026-03-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0013_add_question_bank'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examresult',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='exam',
            name='max_attempts',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='exam',
            name='retake_policy',
            field=models.CharField(choices=[('none', 'No Retakes'), ('best_score', 'Keep Best Score'), ('latest_score', 'Keep Latest Score'), ('average_score', 'Average All Attempts')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='examresult',
            name='attempt_number',
            field=models.IntegerField(default=1),
        ),
    ]
