# Generated by Django 6.0.1 on 2026-03-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0016_practice_exam_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examphoto',
            name='photo',
            field=models.ImageField(upload_to='examphotos/'),
        ),
    ]
