# Generated by Django 6.0.1 on 2026-03-25 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0017_alter_examphoto_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='question_pool_size',
            field=models.IntegerField(default=0, help_text='Questions per student. 0 = all questions.'),
        ),
        migrations.AddField(
            model_name='exam',
            name='shuffle_options',
            field=models.BooleanField(default=True, help_text='Shuffle multiple choice options per student.'),
        ),
        migrations.AlterField(
            model_name='examphoto',
            name='photo',
            field=models.ImageField(upload_to='exam_photos/'),
        ),
        migrations.CreateModel(
            name='StudentExamSeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_ids', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seeds', to='exams.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_seeds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('exam', 'student')},
            },
        ),
    ]
