# Generated by Django 6.0.1 on 2026-04-07 06:20

from django.db import migrations, models


def backfill_is_draft(apps, schema_editor):
    """All exams that already have questions are not drafts."""
    Exam = apps.get_model('exams', 'Exam')
    Exam.objects.filter(questions__isnull=False).distinct().update(is_draft=False)


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0022_update_issue_report_status_flow'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_draft',
            field=models.BooleanField(default=True, help_text='True until questions are successfully saved. Draft exams are not visible to students or the approval queue.'),
        ),
        migrations.RunPython(backfill_is_draft, migrations.RunPython.noop),
    ]
