# Generated by Django 6.0.1 on 2026-04-07 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0022_update_issue_report_status_flow'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_draft',
            field=models.BooleanField(default=True, help_text='True until questions are successfully saved. Draft exams are not visible to students or the approval queue.'),
        ),
    ]
