# Generated by Django 6.0.1 on 2026-03-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_fix_index_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('exam_created', 'Exam Created'), ('exam_approved', 'Exam Approved'), ('exam_rejected', 'Exam Rejected'), ('exam_taken', 'Exam Taken'), ('exam_submitted', 'Exam Submitted'), ('student_approved', 'Student Approved'), ('student_rejected', 'Student Rejected'), ('profile_updated', 'Profile Updated'), ('password_changed', 'Password Changed'), ('password_reset_requested', 'Password Reset Requested'), ('password_reset', 'Password Reset'), ('documents_uploaded', 'Documents Uploaded'), ('bulk_import_students', 'Bulk Import Students'), ('bulk_approve_students', 'Bulk Approve Students'), ('exam_time_extended', 'Exam Time Extended'), ('results_published', 'Results Published')], max_length=50),
        ),
    ]
