# Generated by Django 6.0.1 on 2026-03-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('exam_created', 'Exam Created'), ('exam_approved', 'Exam Approved'), ('exam_rejected', 'Exam Rejected'), ('exam_started', 'Exam Started'), ('exam_taken', 'Exam Taken'), ('exam_terminated', 'Exam Terminated'), ('exam_submitted', 'Exam Submitted'), ('student_approved', 'Student Approved'), ('student_rejected', 'Student Rejected'), ('profile_updated', 'Profile Updated'), ('password_changed', 'Password Changed'), ('password_reset_requested', 'Password Reset Requested'), ('password_reset', 'Password Reset'), ('documents_uploaded', 'Documents Uploaded'), ('bulk_import_students', 'Bulk Import Students'), ('bulk_approve_students', 'Bulk Approve Students'), ('exam_time_extended', 'Exam Time Extended'), ('exam_time_extended_bulk', 'Exam Time Extended Bulk'), ('results_published', 'Results Published'), ('registration_resubmitted', 'Registration Resubmitted'), ('email_change_requested', 'Email Change Requested'), ('email_changed', 'Email Changed'), ('student_school_id_updated', 'Student School ID Updated')], max_length=50),
        ),
    ]
