from django.urls import path
from .views import (
    get_public_stats,
    get_available_exams, get_exam_results, get_exam_detail, create_exam,
    get_instructor_exams, get_exam_detail_for_instructor, update_exam,
    get_pending_exams, approve_exam, reject_exam, get_approved_exams, save_questions,
    get_exam_results_for_instructor, get_exam_for_taking, submit_exam, grade_exam_result,
    get_pending_results, report_cheating, get_exam_analytics, export_exam_results_csv,
    get_exam_review, get_practice_exams, take_practice_exam, check_practice_answers, submit_practice_exam, get_practice_results,
    import_questions_csv, get_exam_detail_for_dean, record_exam_termination,
    capture_exam_photo, get_exam_photos, extend_exam_time, get_my_time_extensions,
    check_exam_conflicts, get_exam_attempts,
    get_question_bank, save_to_question_bank, delete_from_question_bank, import_from_question_bank,
    start_exam_session, heartbeat_exam_session, end_exam_session, end_exam_session_beacon,
    get_department_exam_stats,
    get_instructor_monitoring,
    list_question_issue_reports, create_question_issue_report, get_question_issue_report_detail,
    add_question_issue_message, update_question_issue_status,
    discard_draft_exam,
    get_draft_exams,
)

urlpatterns = [
    path('public-stats/', get_public_stats, name='public_stats'),
    path('department/exam-stats/', get_department_exam_stats, name='department_exam_stats'),
    path('available/', get_available_exams, name='available_exams'),
    path('practice/', get_practice_exams, name='practice_exams'),
    path('practice/<int:exam_id>/', take_practice_exam, name='take_practice_exam'),
    path('practice/<int:exam_id>/check/', check_practice_answers, name='check_practice_answers'),
    path('practice/<int:exam_id>/submit/', submit_practice_exam, name='submit_practice_exam'),
    path('practice/results/', get_practice_results, name='practice_results'),
    path('results/', get_exam_results, name='exam_results'),
    path('results/pending/', get_pending_results, name='pending_results'),
    path('create/', create_exam, name='create_exam'),
    path('drafts/', get_draft_exams, name='get_draft_exams'),
    path('<int:exam_id>/discard-draft/', discard_draft_exam, name='discard_draft_exam'),
    path('instructor/', get_instructor_exams, name='instructor_exams'),
    path('pending/', get_pending_exams, name='pending_exams'),
    path('approved/', get_approved_exams, name='approved_exams'),
    path('<int:exam_id>/detail/', get_exam_detail_for_instructor, name='exam_detail_instructor'),
    path('<int:exam_id>/dean-detail/', get_exam_detail_for_dean, name='exam_detail_dean'),
    path('<int:exam_id>/update/', update_exam, name='update_exam'),
    path('<int:exam_id>/questions/', save_questions, name='save_questions'),
    path('<int:exam_id>/questions/import/', import_questions_csv, name='import_questions_csv'),
    path('<int:exam_id>/results/', get_exam_results_for_instructor, name='exam_results_instructor'),
    path('<int:exam_id>/results/export/', export_exam_results_csv, name='export_results_csv'),
    path('<int:exam_id>/analytics/', get_exam_analytics, name='exam_analytics'),
    path('<int:exam_id>/approve/', approve_exam, name='approve_exam'),
    path('<int:exam_id>/reject/', reject_exam, name='reject_exam'),
    path('<int:exam_id>/take/', get_exam_for_taking, name='exam_for_taking'),
    path('<int:exam_id>/submit/', submit_exam, name='submit_exam'),
    path('<int:exam_id>/terminate/', record_exam_termination, name='record_termination'),
    path('<int:exam_id>/capture-photo/', capture_exam_photo, name='capture_photo'),
    path('<int:exam_id>/photos/', get_exam_photos, name='get_exam_photos'),
    path('<int:exam_id>/extend-time/', extend_exam_time, name='extend_exam_time'),
    path('<int:exam_id>/my-extensions/', get_my_time_extensions, name='my_time_extensions'),
    path('<int:exam_id>/attempts/', get_exam_attempts, name='get_exam_attempts'),
    path('conflicts/', check_exam_conflicts, name='check_exam_conflicts'),
    path('question-bank/', get_question_bank, name='get_question_bank'),
    path('question-bank/save/', save_to_question_bank, name='save_to_question_bank'),
    path('question-bank/<int:bank_id>/delete/', delete_from_question_bank, name='delete_from_question_bank'),
    path('<int:exam_id>/question-bank/import/', import_from_question_bank, name='import_from_question_bank'),
    path('<int:exam_id>/session/start/', start_exam_session, name='start_exam_session'),
    path('<int:exam_id>/session/heartbeat/', heartbeat_exam_session, name='heartbeat_exam_session'),
    path('<int:exam_id>/session/end/', end_exam_session, name='end_exam_session'),
    path('<int:exam_id>/session/end-beacon/', end_exam_session_beacon, name='end_exam_session_beacon'),
    path('monitoring/', get_instructor_monitoring, name='instructor_monitoring'),
    path('report-issues/', list_question_issue_reports, name='list_question_issue_reports'),
    path('report-issues/<int:report_id>/', get_question_issue_report_detail, name='get_question_issue_report_detail'),
    path('report-issues/<int:report_id>/messages/', add_question_issue_message, name='add_question_issue_message'),
    path('report-issues/<int:report_id>/status/', update_question_issue_status, name='update_question_issue_status'),
    path('<int:exam_id>/report-issues/', create_question_issue_report, name='create_question_issue_report'),
    path('<int:exam_id>/report-cheating/', report_cheating, name='report_cheating'),
    path('result/<int:result_id>/grade/', grade_exam_result, name='grade_exam_result'),
    path('result/<int:result_id>/review/', get_exam_review, name='get_exam_review'),
    path('<int:exam_id>/', get_exam_detail, name='exam_detail'),
]
