# Generated by Django 6.0.1 on 2026-03-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_otptoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_otp_verified',
            field=models.DateField(blank=True, help_text='Last date student completed OTP verification', null=True),
        ),
    ]
