# Generated by Django 6.0.1 on 2026-03-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_user_last_otp_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('BSHM', 'Hospitality Management'), ('BSIT', 'Information Technology'), ('BSEE', 'Electrical Engineering'), ('BSBA', 'Business Administration'), ('BSCRIM', 'Criminology'), ('BSED', 'Education'), ('BSCE', 'Civil Engineering'), ('BSChE', 'Chemical Engineering'), ('BSME', 'Mechanical Engineering'), ('GENERAL', 'General Education')], default='GENERAL', max_length=10),
        ),
    ]
