# Generated by Django 6.0.1 on 2026-03-21 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_preregistrationotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrolledStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('BSHM', 'Hospitality Management'), ('BSIT', 'Information Technology'), ('BSEE', 'Electrical Engineering'), ('BSBA', 'Business Administration'), ('BSCRIM', 'Criminology'), ('BSED', 'Education'), ('BSCE', 'Civil Engineering'), ('BSChE', 'Chemical Engineering'), ('BSME', 'Mechanical Engineering')], max_length=10)),
                ('year_level', models.CharField(choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', '4th Year')], max_length=1)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'enrolled_students',
                'ordering': ['department', 'last_name'],
            },
        ),
    ]
