# Generated by Django 6.0.1 on 2026-03-22 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_enrolled_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_rejected',
            field=models.BooleanField(default=False, help_text='Whether the student registration was rejected'),
        ),
    ]
