# Generated by Django 6.0.1 on 2026-03-22 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_user_is_rejected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_otp_verified',
        ),
        migrations.DeleteModel(
            name='OTPToken',
        ),
    ]
