# Generated by Django 6.0.1 on 2026-04-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_preregistrationotp_token_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolledstudent',
            name='course',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='enrolledstudent',
            name='enrolled_subjects',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='account_source',
            field=models.CharField(choices=[('self_registration', 'Self Registration'), ('masterlist_import', 'Masterlist Import')], default='self_registration', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='course',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='user',
            name='enrolled_subjects',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
