# Generated by Django 6.0.1 on 2026-04-16 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_backfill_masterlist_student_approval'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrolledstudent',
            options={},
        ),
    ]
