# Generated by Django 6.0.1 on 2026-03-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('exam_approved', 'Exam Approved'), ('exam_scheduled', 'Exam Scheduled'), ('exam_reminder', 'Exam Reminder'), ('result_published', 'Result Published'), ('account_approved', 'Account Approved'), ('time_extended', 'Time Extended')], max_length=20),
        ),
    ]
