# Generated by Django 6.0.1 on 2026-03-31 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('announcement', 'Announcement'), ('issue_report', 'Issue Report'), ('exam_approved', 'Exam Approved'), ('exam_scheduled', 'Exam Scheduled'), ('exam_reminder', 'Exam Reminder'), ('exam_warning', 'Exam Warning'), ('exam_blocked', 'Exam Blocked'), ('result_published', 'Result Published'), ('account_approved', 'Account Approved'), ('time_extended', 'Time Extended')], max_length=20),
        ),
    ]
