from django.urls import path
from .views import (
    RegisterView, CustomLoginView, get_user_profile, test_email_config,
    get_department_users, get_pending_students, get_rejected_students, approve_student, reject_student,
    update_profile, change_password, bulk_approve_students,
    request_password_reset, request_password_reset_direct, generate_password_reset_otp, reset_password, validate_reset_token, verify_reset_code,
    bulk_import_students, download_student_template, upload_documents,
    save_push_token,
    verify_registration_email, resend_registration_email_otp, update_registration_email,
    pre_verify_email, confirm_pre_verify_email, generate_pre_verify_otp,
    get_enrolled_record, update_student_school_id, resubmit_registration,
    get_department_stats,
    request_email_change, resend_email_change_otp, verify_email_change, generate_email_change_otp,
    list_enrolled_students, add_enrolled_student, delete_enrolled_student,
    import_enrolled_students_csv, download_enrolled_template, sync_masterlist_accounts,
    set_extra_approval, set_declaration_verification, set_id_photo_verification, get_study_load_signed_url, proxy_study_load,
    StrictTokenRefreshView,
)

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('register/pre-verify-email/', pre_verify_email, name='pre_verify_email'),
    path('register/generate-pre-verify-otp/', generate_pre_verify_otp, name='generate_pre_verify_otp'),
    path('register/confirm-pre-verify/', confirm_pre_verify_email, name='confirm_pre_verify_email'),
    path('register/verify-email/', verify_registration_email, name='verify_registration_email'),
    path('register/resend-email-otp/', resend_registration_email_otp, name='resend_registration_email_otp'),
    path('register/update-email/', update_registration_email, name='update_registration_email'),
    path('login/', CustomLoginView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', StrictTokenRefreshView.as_view(), name='token_refresh'),
    path('profile/', get_user_profile, name='user_profile'),
    path('profile/update/', update_profile, name='update_profile'),
    path('profile/email-change/request/', request_email_change, name='request_email_change'),
    path('profile/email-change/resend/', resend_email_change_otp, name='resend_email_change_otp'),
    path('profile/email-change/verify/', verify_email_change, name='verify_email_change'),
    path('profile/change-password/', change_password, name='change_password'),
    path('profile/push-token/', save_push_token, name='save_push_token'),
    path('password-reset/request/', request_password_reset, name='request_password_reset'),
    path('password-reset/request-direct/', request_password_reset_direct, name='request_password_reset_direct'),
    path('password-reset/generate-otp/', generate_password_reset_otp, name='generate_password_reset_otp'),
    path('profile/email-change/generate-otp/', generate_email_change_otp, name='generate_email_change_otp'),
    path('password-reset/verify-code/', verify_reset_code, name='verify_reset_code'),
    path('password-reset/reset/', reset_password, name='reset_password'),
    path('password-reset/validate/', validate_reset_token, name='validate_reset_token'),
    path('department/users/', get_department_users, name='department_users'),
    path('stats/department/', get_department_stats, name='department_stats'),
    path('students/pending/', get_pending_students, name='pending_students'),
    path('students/rejected/', get_rejected_students, name='rejected_students'),
    path('students/bulk-approve/', bulk_approve_students, name='bulk_approve_students'),
    path('profile/upload-documents/', upload_documents, name='upload_documents'),
    path('students/bulk-import/', bulk_import_students, name='bulk_import_students'),
    path('students/template/', download_student_template, name='download_student_template'),
    path('students/<int:student_id>/approve/', approve_student, name='approve_student'),
    path('students/<int:student_id>/reject/', reject_student, name='reject_student'),
    path('students/<int:student_id>/enrolled-record/', get_enrolled_record, name='enrolled_record'),
    path('students/<int:student_id>/update-school-id/', update_student_school_id, name='update_student_school_id'),
    path('students/<int:student_id>/extra-approval/', set_extra_approval, name='set_extra_approval'),
    path('students/<int:student_id>/declaration-verify/', set_declaration_verification, name='set_declaration_verification'),
    path('students/<int:student_id>/id-photo-verify/', set_id_photo_verification, name='set_id_photo_verification'),
    path('students/<int:student_id>/study-load-url/', get_study_load_signed_url, name='get_study_load_signed_url'),
    path('students/<int:student_id>/study-load/', proxy_study_load, name='proxy_study_load'),
    path('students/resubmit/', resubmit_registration, name='resubmit_registration'),
    path('enrolled-records/', list_enrolled_students, name='list_enrolled_students'),
    path('enrolled-records/add/', add_enrolled_student, name='add_enrolled_student'),
    path('enrolled-records/import/', import_enrolled_students_csv, name='import_enrolled_students_csv'),
    path('enrolled-records/sync-accounts/', sync_masterlist_accounts, name='sync_masterlist_accounts'),
    path('enrolled-records/template/', download_enrolled_template, name='download_enrolled_template'),
    path('enrolled-records/<int:record_id>/delete/', delete_enrolled_student, name='delete_enrolled_student'),
    path('debug/email/', test_email_config, name='test_email_config'),
]
